### ISSUE TITLE
1 - create single page with articles

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#1]
## Value proposition

**As a user**
**I want to** see all offered articles
**so that** I can find a list with articles I want to buy.
## Description

![Image](https://user-images.githubusercontent.com/92641651/201887274-14fd5f0d-135e-4697-88a4-0a1e61ca1a0e.png)

## Acceptance Criteria

- the site should  has a header with the app name
- all article cards should displayed in a list
- the latest article is on the top
- every card has a image and a few details of the articles (image, article name, size, gender, price)

## Tasks

- [x] create `Header` component
- [x] create a fake data file (db.json)
- [x] create `Article` component with image, article name, size, gender, price
- [x] fetch the fake data and display it on the page

## Complexity

M
