### ISSUE TITLE
6 - create my Articles Page

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#11]
## Value proposition

**As a ** user
**I want** to have my articles on a separate page
**so that** I have an overview over my articles.

## Description

![Image](https://user-images.githubusercontent.com/92641651/203279945-bc6be94e-5400-449f-b898-8bd3873f5e1d.png)

## Acceptance criteria

- the navbar should have an additional button "Meine Artikel"
- the headline of the my articles page should say "Meine Artikel"
- the page with my articles should display only my article cards
- the article cards should have an icon "I"
- all details should be displayed by clicking on the "I" icon
- the navbar button "Meine Artikel" should be linked with "Meine Artikel" page

## Tasks

- [x] create a feature-branch
- [x] create a `myArticles` page
- [x] create a new button "Meine Artikel" in the navbar 
- [x] link the button to `myArticles` page
- [x] filter by author and display my article cards
- [x] link the icon "I" to the details page

## Complexity

M

**Comment by MeenaFoerderer** [comment]
Hey Eugen, cool feature 🙂
I have a few small suggestions:
 
**Acceptance criteria**
Typos

> - the page with my articles should displayed only my article cards

the page with my articles should only display my article cards

> - the navbar button "Meine Artikel" should linked with the page

the navbar button "Meine Artikel" should be linked with the "Meine Artikel" page

**Tasks**

> - [ ] create a new button "Meine Artikel" in the navbar
> - [ ] link the button to myArticles page
> - [ ] ceate a button in the navbar with a link to the myArticles page

isn't the last task the same as the two others combined? 🤔
Also there is a small typo: ceate --> create

> - [ ] only my created articles should displayed in a list

To me, that's not a task but an acceptance criteria. And you already listed that in your acceptance criteria (point 3)

**Comment by MeenaFoerderer** [comment]
**Value proposition**

> **As a** user
**I want** to see my own created articles
**so that** my articles are displayed at a sepreate page

Typo in the last paragraph: separate

I would suggest to write it as following:
**As a** user
**I want** to have my articles on a separate page
**so that** I have an overview over my articles

**Comment by EugenMoser** [comment]
I love your suggestions. Thanks Meena

**Comment by MeenaFoerderer** [comment]
Approved 🎉
Just one small thing:

> the headline of the my articles page should have "Meine Artikel"

Better: ..should say "Meine Artikel"

And user should not be bold 😶
