### ISSUE TITLE
7 - add edit option

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#12]
## Value proposition

**As a user**
**I want** to edit my article entries
**so that** I can update or correct the entries

## Description

![Image](https://user-images.githubusercontent.com/92641651/203526167-3bd7fc9e-62da-43f7-81a3-941effd53137.png)

## Acceptance criteria

- the details page of my articles should have an edit button
- by clicking the edit button leads to the editable form
- the form should contain the previous entries
- by clicking the "akutalisieren" button I get to details page
-  the article details page should have an icon "X" for closing the edit page and go back to details page

## Tasks

- [x] create a feature-branch
- [x] add an edit button to my aritcle details page
- [x] link the edit button to the editable form
- [x] fill the form with the previous entries
- [x] link to the details page after the submit
- [x] create an "X" icon to close the page and go back to details page
​

## Complexity

M

**Comment by gaiisay** [comment]
Du hast nur ein paar typos: akutualisieren und dropedown. Aber der rest ist okay
