### ISSUE TITLE
8 - add delete option

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#13]
## Value proposition

**As a user**
**I want** to delete my article card
**so that I**  can remove articles from my article list

## Description

![Image](https://user-images.githubusercontent.com/92641651/203519224-cbb4f398-1efb-45d7-99e1-df0f8351aeef.png)

## Acceptance criteria

- the details page of my articles should have a delete button
- the delete button leads to a modal which asks "willst du deinen Artikel wirklich löschen"
- the modal should have two buttons "löschen" and "abbrechen"
- by clicking "löschen" the article should be deleted and the user will be redirected to the "my article" page
- by clicking "abbrechen" the modal should close (without delete) and go back to "my details" page

## Tasks

- [x] create a feature-branch
- [x] create a delete button "löschen" 
- [x] create a `DeleteArticle` modal component
- [x] link the delete button to the modal component
- [x] create "abbrechen" and  "löschen" button in the modal component
- [x] create delete function on submit the löschen button
- [x] link the "abbrechen" button  to the details page
- [x] link the "löschen" button to the "Meine Artikel" page

## Complexity

S

**Comment by BucherLara** [comment]
Hello Eugen, this looks very nice ! Just some small things, in you value proposition is a little typo ( **so that I ** can) and maybe you can add "Favorite" List, so that its clear, that you want to be able to delete items from your own favorites. Maybe you can think about the color of editieren and löschen, its a little confusing. And what happens if you click on the cross symbol on the modal instead of "abbrechen" where do you land?

**Comment by EugenMoser** [comment]
thanks Lara

**Comment by GregOnOff** [comment]
Seems good. Nice job Eugen! ps. the typo is still there... wrap the ' I ' within the asterisk
