### ISSUE TITLE
9 - styling pages

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#17]
## Value proposition

**As a **user
**I want** a clear and readable context with a clear button-style
**so that I**  can easily navigate through the app.

## Acceptance criteria

- the pages should have margin and padding
- the images should be responsive
- the buttons should have unique icons
- the pages, buttons, fonts should be easily readable 
- the navbar should displayd the page location 

## Tasks

- [x] create a feature-branch
- [x] create styled components for header, navbar, pages, buttons, icons
- [x] add style for the components
  - [x] change font
  - [x] change background color
  - [x] change background color for article cards
  - [x] change button icons and style
  - [x] add curser pointer to buttons
  - [x] change navbar style
  - [x] change header style
  - [x] change modal style
  - [x] change hyperlinks style

## Complexity

L
