### ISSUE TITLE
12 - dropdown for size (Größe)

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#18]
## Value proposition

**As a **user
**I want** to select the size
**so that I**  can't enter a wrong value

## Description

![Image](https://user-images.githubusercontent.com/92641651/204303634-9d6c4a13-5d7f-463a-94a7-9c3435930524.png)

## Acceptance criteria

- the "verkaufen"page should have a dropdown selection for the size
- the dropdown should have all baby and children sizes to choose from

## Tasks

- [ ] create a feature-branch
- [ ] create dropdown for the size at "verkaufen" page
- [ ] add all sizes as select option

## Complexity

S
