### ISSUE TITLE
?? - information button sizetable for "Größe"

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#19]
## Value proposition

**As a** user
**I want** to see a size chart
**so that I**  can choose the right size

## Description

![Image](https://user-images.githubusercontent.com/92641651/204305755-371af11d-3c8e-475f-a41a-203c37cc816c.png)

## Acceptance criteria

- the details page should have an information button next the size
- clicking the button should open size chart
- the size chart should have an icon for close the size chart and go back to the details page

## Tasks

- [ ] create a feature-branch
- [ ] add an icon for size chart information
- [ ] create a function to show the size chart in a modal
- [ ] add an icon "X" to close the modal and go back to details page

## Complexity

M

**Comment by SirJohn42Walker** [comment]
Looks great
