### ISSUE TITLE
2 - create a article details page

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#2]
## Value Proposition

**As a** user  
**I want to** see all details of a article  
**so that** I can better decide for a purchas
​

## Description

![userStory_02-1](https://user-images.githubusercontent.com/92641651/201902677-f778586e-7cae-4165-9f75-928377a88079.png)
​
![userStory_02-2](https://user-images.githubusercontent.com/92641651/201902696-3c4f4fb0-cbd7-4f25-ab0c-4707be4ba38e.png)

## Acceptance Criteria

- [ ] the article card should have a "I" icon
- [ ] all details should be displayed by clicking on the "I" icon
- [ ] the article page with all details should contain the following details:
      image, Artikel, Preis, Größe, Geschlecht, Zustand, Tierhaushalt, Raucherhaushalt, kurze Beschreibung, Entfernung
- [ ] the article details page should hav it`s own headline "Artikel"
- [ ] the article details page should have a icon "X" for closing the details and go back to homepage
      ​
## Tasks

- [x] create a feature-branch
- [x] create a `articleDetails` page
- [x] create a icon with a link to the `articleDetails`
- [x] the articleDetails should display in a new page (Modal)
- [x] link the icon to the articleDetails
- [x] render all details at articleDetails
- [x] create an "X" icon to close the page and go back to homepage
      ​
## Complexity

L

**Comment by JulianHrt** [comment]
very clear and concrete

**Comment by ahohnsen** [comment]
Hey Eugen,

Well done. I have two suggestions:

Value Proposition: Your second and third line are almost identical. The last line should describe the value for the user. Why does the user want to see more details of an article? So that the user can decide more easily if he/she wants to buy the article. :) 

Additionally, it would be good to mention in the acceptance criteria, what happens when the user clicks on the "x" icon. Little reminder: All possible user interactions should be described in the acceptance criteria.

**Comment by EugenMoser** [comment]
thanks Andrea + Julian for your feedbacks
