### ISSUE TITLE
10 - upload image

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#20]
## Value proposition

**As a**  user
**I want** to add an image of my article
**so that I**  can show the article to the potential buyer

## Description

![Image](https://user-images.githubusercontent.com/92641651/204295618-72a340b8-02c8-4d28-aa22-93f95a8d3b3a.png)

## Acceptance criteria

- the "verkaufen" page should have an optional upload image option
- the "editieren" page should have an optional upload image option for replacing the current image
- the image should be displayed at the article cards and article details

## Tasks

- [ ] create a feature-branch
- [ ] add an image upload icon to "verkaufen" and "editieren" page
- [ ] create a upload image function by clicking the icon

## Complexity

L

**Comment by ahohnsen** [comment]
Hey Eugen,

I think the acceptance criteria could be a bit more detailed:

- What happens if the user clicks on the upload button? E.g. a window opens to choose a file from the computer...
- How does it look like once a picture is uploaded? Is there a preview? Once a picture is uploaded, is there still the upload-button displayed, so the user can change the picture?
