### ISSUE TITLE
11 - search bar

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#23]
## Value proposition

**As a **user
**I want** to search for articles
**so that I**  can find quickly the articles I am looking for 

## Description

![Image](https://user-images.githubusercontent.com/92641651/205923565-e9dc5c0f-7cf0-44a2-9b49-c0ac5a9dbc61.png)

## Acceptance criteria

- the app should have a search page
- the search page should have searchbar
- you should be able to search for the article name
- when typing the article name you should see the results below the serchbar
- if the serachbar is empty all articles should be displayed
 

## Tasks

- [ ] create a feature-branch
- [ ] create a `search` page
- [ ] create searchbar component
- [ ] add props from the component to the homepage
- [ ] add the search function to the searchbar

## Complexity

L
