### ISSUE TITLE
13 - bookmark page

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#27]
## Value proposition

**As a** user
**I want** to save my favorite articles
**so that I**  have a page with a overview of my favorite articles.

## Description

![Image](https://user-images.githubusercontent.com/92641651/206395754-5322ccfd-74c1-4c6c-a71f-37b57aa1cd8e.png)

## Acceptance criteria

- each article card has a favorite button
- by clicking the favorite button the article is saved on the "Merkliste" page
- by clicking the favorite button again the article card will be removed from the "Merkliste" page
- the navigation bar should have an icon for the "Merkliste" page for the navition to this page

## Tasks

- [ ] create a feature-branch
- [ ] create a "Merkliste" page
- [ ] add an icon for the "Merkliste" page to the navigationbar
- [ ] link the "Merkliste" page with the icon
- [ ] add a toogle icon to the article cards
- [ ] create a toogle function 
- [ ] add a headline to header

## Complexity

L
