### ISSUE TITLE
3 - create a contact button with seller contact

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#3]
## Value proposition

**As a user**
**I want** to see the seller contact informations
**so that** I can contact the seller tu purchase the article.

## Description

![Image](https://user-images.githubusercontent.com/92641651/201908431-782b7828-f724-4788-b281-d643c5c73d79.png)

## Acceptance criteria

- [ ] the ArticleDetails should have a contact button
- [ ] by clicking the button a modal will displayed
- [ ] the contact popup should have the seller name, a phone number with trigger and a email adress with trigger
- [ ] the contact page should have a close icon "X" for closing the contact informations and go back to article details page

- 

## Tasks

- [x] create a feature-branch
- [x] create a contact button
- [x] create a contact modal window
- [x] link the button to the contact informations
- [x] create an icon to close the page and go back to ArticleDetails
- [x] add a hyperlink to phone (`tel:...`) that allow call directly with the mobile phone 
- [x] add a hyperlink to email (`mailto:...`) that allow send a email directly with the email progarm

## Complexity

M

**Comment by FelineHuhn** [comment]
Hey Eugen, the wireframes are very pixelated, maybe you could choose another way of uploading the wireframes, so you can read it better? 
And maybe you can add to the ACC's at second place: "by clicking the contact button a pop-up will be displayed"

Otherwise everything loos fine to me. Good job :)

**Comment by EugenMoser** [comment]
thanks a lot for your feedback Feline!

**Comment by ahohnsen** [comment]
Hey Eugen,

I have a few suggestions:

- Please have a look at your value proposition. You should follow this guideline:
 
As a `ROLE`
I want to `ACTIVITY`
so that `DESIRED USER VALUE`

So if you have a look at your value proposition again, what you have written in the third line actually belongs into the second one. Meaning the activity would be "to see the contact information of the seller" and the desired user value would be something like "so that I can contact the seller to purchase the item".

Acceptance Criteria:
- I think you mean a modal and not a pop-up 🤔 
- Please remember to describe all possible user interactions -> How can the user close the modal? What happens if the user clicks on the "x"?
- You have written that the email and phone number have a "trigger". Maybe you can rephrase that part to make it more clear what you mean.
