### ISSUE TITLE
4 - navbar and create new articles

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#7]
## Value Proposition

**As a** user  
**I want to** navigate to a sell page  
**so that** I can sell my own articles
​

## Description

![Image](https://user-images.githubusercontent.com/92641651/202680277-37f81486-4fa1-4906-b1f4-e7a2a06ec84e.png)

## Acceptance Criteria

- [x] each page should have a navigation bar
- [x] the navbar should have a "Home" and a "verkaufen" button
- [x] the "Home" button should navigate to the home page
- [x] the "verkaufen" button should navigate to the sell page
- [x] the headline of the sell page should have "Artikel verkaufen"
- [x] the sell page should have a form with all details
  - [x] the required details are "Artikel", "Größe", "Preis", "Geschlecht", "Zustand"
  - [x] the optional details are "Tierhaushalt", "Raucherhaushalt" and "kurze Beschreibung
  - [x] the details "Artikel", "Größe", "Preis" and "kurze Beschreibung" are input fields
  - [x] the details "Geschlecht" and "Zustand" are dropdown selections
  - [x] the details "Tierhaushalt" and "Raucherhaushalt" are checkboxes
- [x] the sell page should have a close icon "X" for closing the contact informations and go back to home page

## Tasks

- [x] create a feature branch
- [x] create a `Navbar` component
- [x] put the `Navbar` component into the layout component
- [x] create a button "Home" and  "verkaufen" in the navbar
- [x] create a "artikelVerkaufen" page
- [x] change the headline in "Artikel hinzufügen" (with useRoute)
- [x] add form to the page with following details
    - [x] "Artikel" input field is required
    - [x] "Preis" input field is required
    - [x] "Größe" input field is required
    - [x] "Geschlecht" select option is required
    - [x] "Zustand" select option is required
    - [x] "Tierhaushalt" checkbox is optional
    - [x] "Raucherhaushalt" checkbox is optional
    - [x] "kurze Beschreibung" textarea is optional
    - [x] "Preis" number input is required
 - [x]  create an icon to close the page and go back to homepage
      ​

## Complexity

L

**Comment by StefanFitoussi** [comment]
Hey Eugen, I think in TASKS the "Tierhaushalt"-checkbox and the "Raucherhaushalt"-checkbox are supposed to be both optional, not required. If that is right and you change it you are good to go! :)

**Comment by EugenMoser** [comment]
Hey Stefan, thanks for your feedback.
