### ISSUE TITLE
5 - sell button / sell article

### ISSUE THREAD

**Issue by EugenMoser** [EugenMoser/capstone-project#8]
## Value proposition

**As a user**
**I want** to submit my entered article
**so that** the article is displayed for potential buyers

## Description

![Image](https://user-images.githubusercontent.com/92641651/202762874-2b5f5f22-212c-4eae-b920-50befee5d5b5.png)

## Acceptance criteria

- [x] the ArticleSell page should have a sell button
- [x] by clicking the button the entries should be saved in local Storage
- [x] go to homepage when clicking
- [x] the homepage should displayed the new created article

- 

## Tasks

- [x] create a feature-branch
- [x] create a sell button
- [x] create onClick function to save the entries in local Storage
- [x] link the button to the homepage

## Complexity

S

**Comment by gaiisay** [comment]
Looks pretty good
